export const GET_ALL_WORKSPACES =
  'DATA_AUTOMATION/FETCH/ALL/WORKSPACE';
export const GET_ALL_WORKSPACES_SUCCESS =
  'DATA_AUTOMATION/FETCH/ALL/WORKSPACE/SUCCESS';
export const CREATE_WORKSPACES_SUCCESS =
  'DATA_AUTOMATION/CREATE/NEW/WORKSPACE/SUCCESS';
export const CREATE_WORKSPACE =
  'DATA_AUTOMATION/CREATE/NEW/WORKSPACE';

export const GET_ALL_WORKBOOKS =
  'DATA_AUTOMATION/FETCH/ALL/WORKBOOKS';
export const GET_ALL_WORKBOOKS_SUCCESS =
  'DATA_AUTOMATION/FETCH/ALL/WORKBOOKS/SUCCESS';
export const CREATE_WORKBOOK_SUCCESS =
  'DATA_AUTOMATION/CREATE/NEW/WORKBOOK/SUCCESS';
export const CREATE_WORKBOOK = 'DATA_AUTOMATION/CREATE/NEW/WORKBOOK';
